//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SZYBYDY_WOJCIUK_SACHARCZUK_PAWLENKO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int ID { get; set; }
        public int Student_ID { get; set; }
        public int Subject_ID { get; set; }
        public string Value { get; set; }
        public bool IsFinal { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
